(function(root){'use strict';
function bounded(v,min,max,name){if(!Number.isFinite(v)||v<min||v>max)throw new RangeError(name+' outside supported range');return v;}
function miura(fold,n=13,a=2.7,b=2.7,gamma=60){bounded(fold,0,90,'Fold');bounded(gamma,.01,89.99,'Sector angle');if(!Number.isInteger(n)||n<1||n>100||!Number.isFinite(a)||!Number.isFinite(b)||a<=0||b<=0)throw new RangeError('Invalid sheet dimensions');const t=fold*Math.PI/180,g=gamma*Math.PI/180,q=Math.sqrt(1-Math.sin(g)**2*Math.sin(t)**2),L=a*q,h=a*Math.sin(g)*Math.sin(t),s=b*Math.cos(g)/q,W=b*Math.sin(g)*Math.cos(t)/q;
 const vertices=[];for(let j=0;j<=n;j++)for(let i=0;i<=n;i++)vertices.push([i*L+(j%2)*s-(n*L+s)/2,j*W-n*W/2,(i%2)*h-h/2]);
 return{vertices,a,b,gamma,fold,L,W,h,s,acrossI:2*fold,acrossJ:2*Math.atan2(Math.cos(g)*Math.sin(t),Math.cos(t))*180/Math.PI,zeroThickness:true};}
function rotate13(vector,i,j,degrees){if(!Array.isArray(vector)||vector.length!==13||!vector.every(Number.isFinite))throw new TypeError('Thirteen finite normalized coordinates are required');if(!Number.isInteger(i)||!Number.isInteger(j)||i<0||j<0||i>12||j>12||i===j)throw new RangeError('Choose two distinct dimensions');bounded(degrees,-360,360,'Rotation');const t=degrees*Math.PI/180,c=Math.cos(t),s=Math.sin(t),out=[...vector];out[i]=c*vector[i]-s*vector[j];out[j]=s*vector[i]+c*vector[j];return out;}
function project13(vector){if(!Array.isArray(vector)||vector.length!==13||!vector.every(Number.isFinite))throw new TypeError('Expected thirteen finite coordinates');return{visible:vector.slice(0,3),residual:vector.slice(3),norm:Math.hypot(...vector),residualNorm:Math.hypot(...vector.slice(3))};}
function resonance(l,c){bounded(l,.01,100,'Inductance nH');bounded(c,.01,100,'Capacitance pF');return 1/(2*Math.PI*Math.sqrt(l*1e-9*c*1e-12))/1e9;}
const add=(a,b)=>[a[0]+b[0],a[1]+b[1]],mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],scale=(a,k)=>[a[0]*k,a[1]*k];
function mm(a,b){return[[add(mul(a[0][0],b[0][0]),mul(a[0][1],b[1][0])),add(mul(a[0][0],b[0][1]),mul(a[0][1],b[1][1]))],[add(mul(a[1][0],b[0][0]),mul(a[1][1],b[1][0])),add(mul(a[1][0],b[0][1]),mul(a[1][1],b[1][1]))]];}
function circuit(frequency,{capacitance=.75,inductance=2.2,crease=1.5,resistance=.08,delay=10}={}){bounded(frequency,.01,100,'Frequency GHz');bounded(capacitance,.01,100,'Capacitance pF');bounded(inductance,.01,100,'Inductance nH');bounded(crease,0,100,'Crease nH');bounded(resistance,0,100,'Resistance ohm');bounded(delay,0,1000,'Delay ps');const w=2*Math.PI*frequency*1e9,Z=50,phase=w*delay*1e-12,co=Math.cos(phase),si=Math.sin(phase),branch=w*inductance*1e-9-1/(w*capacitance*1e-12),zb=[0,branch],zs=[resistance,w*crease*1e-9],T=[[[co,0],[0,Z*si]],[[0,si/Z],[co,0]]],S=[[[1,0],zs],[[0,0],[1,0]]],H=[[zb,[0,0]],[[1,0],zb]],M=mm(mm(mm(T,S),H),T),den=add(add(M[0][0],scale(M[0][1],1/Z)),add(scale(M[1][0],Z),M[1][1])),num=scale(zb,2),abs2=den[0]**2+den[1]**2;let re=(num[0]*den[0]+num[1]*den[1])/abs2,im=(num[1]*den[0]-num[0]*den[1])/abs2;if(Math.abs(branch)<1e-12){re=0;im=0;}const magnitude=Math.hypot(re,im),db=magnitude===0?null:20*Math.log10(magnitude);return{frequency,re,im,magnitude,s21dB:db,insertionLoss:db===null?null:-db,phaseDeg:magnitude===0?null:Math.atan2(im,re)*180/Math.PI,idealNotch:magnitude===0,lcNotchGHz:resonance(inductance,capacitance)};}
const api={miura,rotate13,project13,resonance,circuit};if(typeof module==='object'&&module.exports)module.exports=api;else root.OrigamiEngineering=api;
})(globalThis);
